### ISSUE TITLE
댓글 UI/UX 개선

### ISSUE THREAD

**Issue by liberaldev** [SeaniaTwix/community#8]
현재 댓글 UI/UX는 이질적이라서 경로의존성 등에서의 문제가 많습니다. 한국의 게시판은 물론이고 서양의 포럼또한 댓글 창을 플로트로 두는 경우가 흔하지 않습니다. 따라서 댓글 UI를 다음과 같이 개선할 것을 제안합니다.

- 댓글의 경우 플로팅이 아닌 루리웹과 똑같이 아래에 댓글창이 출력되도록 합니다.
- 대댓글의 경우 대댓글을 쓸때 해당 댓글의 아래에 입력창이 노출이 되도록 했으면 합니다.

**Comment by SeaniaTwix** [comment]
해당 기능은 주요 기능이므로 변경할 예정이 없습니다.
